Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/*

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Exclude:
    - cat_ipsum.gemspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
