module CatIpsum
  CAT_ACTIONS = [
    'all of a sudden',
    'attack feet',
    'behind the couch',
    'burrow under covers',
    'cat snacks',
    'chase imaginary bugs',
    'chase mice',
    'chew foot',
    'chew ipad power cord',
    'claw drapes',
    'climb leg',
    'destroy couch',
    'find something else more interesting',
    'flop over',
    'give attitude',
    'go crazy',
    'hate dog',
    'hide when guests come over',
    'hunt anything that moves',
    'ignore the human',
    'inspect anything brought into the house',
    'intently sniff hand',
    'intently stare at the same spot',
    'intrigued by the shower',
    'leave dead animals as gifts',
    'leave hair everywhere',
    'mark territory',
    'missing until dinner time',
    'nap all day',
    'or need to chase tail',
    'play time',
    'purr',
    'rub face on everything',
    'run in circles',
    'shake treat bag',
    'sleep on keyboard',
    'stand in doorway',
    'stand in front of the computer screen',
    'stare at ceiling',
    'stick butt in face',
    'stretch',
    'sun bathe',
    'swat at dog',
    'sweet beast',
    'throwup on your pillow',
    'under the bed',
    'use lap as chair',
    'why must they do that',
    'yawn so much'
  ]
end
